baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Will Coughlin'
theme = 'typo'

[params]
# Appearance settings
theme = 'auto'

# Intro on main page, content is markdown
homeIntroTitle = ''
homeIntroContent = """
I am a software engineer and data science student working in the energy industry. My current technical work involves supporting and developing 
tools for CI/CD and code quality. I most commonly find myself working with tools like GitHub Actions, Docker, and Terraform; and languages 
including Java, Kotlin, and JavaScript.

In my graduate studies, I have aquired project experience with Python, R, machine learning, and data pipelines. Take a look at my projects 
page for some highlights!
"""

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/coughlinwf/"

[[params.social]]
name = "github"
url = "https://github.com/willcoughlin"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "projects"
url = "/projects"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'
