name: Gatsby Publish

on:
  push:
    branches:
      - TestMyGatsbyAction

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: willcoughlin/gatsby-gh-pages-action@TestMyGatsbyAction
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: master
